### ISSUE TITLE
Unknown column 'password' in 'field list'

### ISSUE THREAD

**Issue by cscd98** [vStone/puppet-percona#28]
In Percona 5.7 the password field has been removed and replaced with authentication_string

This fails:

```
percona::rights {'xx@xx':
          database => 'xx',
          priv     => 'select_priv',
          password => 'xx',
        }
```

**Comment by cscd98** [comment]
Is this repo dead?

**Comment by vStone** [comment]
Pretty much. You should probably migrate to the puppetlabs-mysql module. Overriding the default package_name for ::mysql and ::mysql::client should do the trick.

As an alternative, you can take ownership of it or we can attempt to migrate it to the voxpupuli group.
